server:
  port: 8001
  compression.enabled: true
  max-http-header-size: 20000

grpc:
  port: 8002

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
